source = ~/.config/hypr/hyprland-base.conf

workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:DP-2, default:true
workspace = 3, monitor:DP-3, default:true

windowrule {
    name = gaming-discord-ws3
    match:class = discord
    workspace = 3
    no_initial_focus = on
}
windowrule {
    name = gaming-steam-ws1
    match:class = steam
    workspace = 1
}

exec-once = uwsm app -- flatpak run com.discordapp.Discord
exec-once = uwsm app -- steam -tenfoot
exec-once = [workspace 2 silent] uwsm app -- $terminal -e gotop
exec-once = [workspace 2 silent] uwsm app -- $terminal -e nvtop

# Want color accurate gaming
exec = sleep 1; hyprctl hyprsunset identity
