FROM docker.io/archlinux:base-devel

RUN pacman -Syu --noconfirm \
  fish starship neovim zellij git tree-sitter-cli ripgrep \
  rust rust-analyzer mold cargo-nextest cargo-expand cargo-bloat cargo-geiger \
  vscode-html-languageserver prettier \
  wayland wayland-protocols
